model: "wandb://fixie/ultravox/model-zhuang.2024-08-21-ultravox.medium-1j:v5"
report_logs_to: ["wandb"]
batch_size: 50
output_dir: "./output"
dataset_configs:
  - alias: "covost2-en_de"
    path: "fixie-ai/covost2"
    name: "en_de"
    splits:
      - "test"
    user_template: "Please translate the text to German. Your response should only include the German translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_zh"
    path: "fixie-ai/covost2"
    name: "en_zh-CN"
    splits:
      - "test"
    user_template: "Please translate the text to Chinese. Your response should only include the Chinese translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 15531
    eval_config:
      metric: "bleu"
      args:
        tokenize: "zh"
  - alias: "covost2-en_ar"
    path: "fixie-ai/covost2"
    name: "en_ar"
    splits:
      - "test"
    user_template: "Please translate the text to Arabic. Your response should only include the Arabic translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-en_ca"
    path: "fixie-ai/covost2"
    name: "en_ca"
    splits:
      - "test"
    user_template: "Please translate the text to Catalan. Your response should only include the Catalan translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 15531
    eval_config:
      metric: "bleu"
  - alias: "covost2-es_en"
    path: "fixie-ai/covost2"
    name: "es_en"
    splits:
      - "test"
    user_template: "Please translate the text to English. Your response should only include the English translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 13221
    eval_config:
      metric: "bleu"
  - alias: "covost2-ru_en"
    path: "fixie-ai/covost2"
    name: "ru_en"
    splits:
      - "test"
    user_template: "Please translate the text to English. Your response should only include the English translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 6300
    eval_config:
      metric: "bleu"
  - alias: "covost2-zh_en"
    path: "fixie-ai/covost2"
    name: "zh-CN_en"
    splits:
      - "test"
    user_template: "Please translate the text to English. Your response should only include the English translation, without any additional words:\n\n<|audio|>"
    assistant_template: "{{ translation }}"
    transcript_template: "{{ sentence }}"
    total_samples: 4898
    eval_config:
      metric: "bleu"